"""
models/interview.py
═══════════════════════════════════════════════════════
Interview session data models for the Autonomous Hiring Agent.
Used by the Interviewer Agent (Groq llama-4-maverick)
to manage multi-round autonomous chat interviews.

All models use Pydantic v2.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────
#  Enums
# ─────────────────────────────────────────────────────

class InterviewType(str, Enum):
    """Type of interview round."""
    SCREENING       = "screening"       # round 1 — basic fit check
    TECHNICAL       = "technical"       # round 2 — deep tech questions
    CULTURAL        = "cultural"        # round 3 — values, teamwork, final


class MessageRole(str, Enum):
    """Who sent the message in the chat."""
    AGENT       = "agent"       # interviewer AI
    APPLICANT   = "applicant"   # candidate response


class QuestionCategory(str, Enum):
    """Category of interview question asked."""
    INTRODUCTION        = "introduction"
    TECHNICAL_CONCEPT   = "technical_concept"
    CODING_PROBLEM      = "coding_problem"
    SYSTEM_DESIGN       = "system_design"
    PAST_EXPERIENCE     = "past_experience"
    BEHAVIORAL          = "behavioral"
    CULTURE_FIT         = "culture_fit"
    CLOSING             = "closing"


class ResponseQuality(str, Enum):
    """Quality rating of an applicant's response."""
    EXCELLENT   = "excellent"   # 90–100
    GOOD        = "good"        # 70–89
    AVERAGE     = "average"     # 50–69
    POOR        = "poor"        # 30–49
    NO_ANSWER   = "no_answer"   # blank or irrelevant


class SessionStatus(str, Enum):
    """Current state of the interview session."""
    SCHEDULED   = "scheduled"
    IN_PROGRESS = "in_progress"
    COMPLETED   = "completed"
    ABANDONED   = "abandoned"   # applicant dropped off
    FAILED      = "failed"      # system error


# ─────────────────────────────────────────────────────
#  Sub-models
# ─────────────────────────────────────────────────────

class InterviewMessage(BaseModel):
    """A single message in the interview chat."""
    role:           MessageRole
    content:        str                     = Field(..., min_length=1)
    timestamp:      datetime                = Field(default_factory=datetime.utcnow)
    token_count:    Optional[int]           = None      # for rate limit tracking


class InterviewQuestion(BaseModel):
    """A question asked during the interview with metadata."""
    question_id:    str
    category:       QuestionCategory
    question_text:  str                     = Field(..., min_length=10)
    expected_topics: list[str]              = Field(default_factory=list)
    difficulty:     int                     = Field(default=3, ge=1, le=5)
    # 1=easy, 2=medium-easy, 3=medium, 4=hard, 5=expert
    asked_at:       datetime                = Field(default_factory=datetime.utcnow)


class InterviewResponse(BaseModel):
    """An applicant's response to a specific question."""
    question_id:    str
    response_text:  str                     = Field(default="")
    response_time_seconds: Optional[int]   = None      # how long they took
    quality:        Optional[ResponseQuality] = None
    score:          Optional[float]         = Field(default=None, ge=0, le=100)
    ai_verdict:     Optional[str]           = None      # from detector agent
    ai_confidence:  Optional[float]         = Field(default=None, ge=0, le=1)
    evaluator_notes: Optional[str]          = None
    responded_at:   datetime                = Field(default_factory=datetime.utcnow)

    def is_ai_generated(self, threshold: float = 0.75) -> bool:
        """Return True if AI confidence exceeds threshold."""
        return (
            self.ai_confidence is not None
            and self.ai_confidence >= threshold
        )

    def is_blank(self) -> bool:
        """Return True if response is empty or too short."""
        return len(self.response_text.strip()) < 20


class RoundSummary(BaseModel):
    """
    Summary of a single interview round.
    Generated by the Interviewer Agent after each round completes.
    """
    round_number:       int                 = Field(..., ge=1, le=3)
    interview_type:     InterviewType
    total_questions:    int                 = 0
    answered:           int                 = 0
    skipped:            int                 = 0
    round_score:        Optional[float]     = Field(default=None, ge=0, le=100)
    ai_flags:           int                 = 0         # number of AI-flagged responses
    key_strengths:      list[str]           = Field(default_factory=list)
    key_weaknesses:     list[str]           = Field(default_factory=list)
    advance_to_next:    Optional[bool]      = None      # should they move to next round?
    summary_text:       Optional[str]       = None
    completed_at:       Optional[datetime]  = None

    def completion_rate(self) -> float:
        """Percentage of questions answered."""
        if self.total_questions == 0:
            return 0.0
        return round((self.answered / self.total_questions) * 100, 1)


# ─────────────────────────────────────────────────────
#  Core Interview Session Model
# ─────────────────────────────────────────────────────

class InterviewSession(BaseModel):
    """
    Full interview session for a single applicant.
    Tracks all rounds, messages, questions, and responses.

    Used by:
    - Interviewer Agent  → conducts the session
    - Detector Agent     → checks responses for AI content
    - Session Store      → persists to Supabase
    - Orchestrator       → decides round advancement
    """

    # ── Identity ──────────────────────────────────
    session_id:         str
    applicant_id:       str
    applicant_name:     str
    role_applied:       str

    # ── Session Config ────────────────────────────
    total_rounds:       int                 = Field(default=3, ge=1, le=3)
    current_round:      int                 = Field(default=1, ge=1, le=3)
    interview_type:     InterviewType       = InterviewType.SCREENING
    model_used:         str                 = "meta-llama/llama-4-maverick-17b-128e-instruct"

    # ── Status ────────────────────────────────────
    status:             SessionStatus       = SessionStatus.SCHEDULED
    started_at:         Optional[datetime]  = None
    completed_at:       Optional[datetime]  = None
    duration_seconds:   Optional[float]     = None

    # ── Conversation History ──────────────────────
    messages:           list[InterviewMessage]  = Field(default_factory=list)

    # ── Questions & Responses ─────────────────────
    questions:          list[InterviewQuestion] = Field(default_factory=list)
    responses:          list[InterviewResponse] = Field(default_factory=list)

    # ── Round Summaries ───────────────────────────
    round_summaries:    list[RoundSummary]  = Field(default_factory=list)

    # ── Final Outcome ─────────────────────────────
    final_score:        Optional[float]     = Field(default=None, ge=0, le=100)
    final_verdict:      Optional[str]       = None      # accept / reject / hold
    overall_notes:      Optional[str]       = None
    total_ai_flags:     int                 = 0

    # ── Validators ────────────────────────────────
    @field_validator("current_round")
    @classmethod
    def round_within_total(cls, v: int, info) -> int:
        total = info.data.get("total_rounds", 3)
        if v > total:
            raise ValueError(f"current_round ({v}) cannot exceed total_rounds ({total})")
        return v

    # ── Methods ───────────────────────────────────
    def add_message(self, role: MessageRole, content: str) -> None:
        """Append a message to conversation history."""
        self.messages.append(
            InterviewMessage(role=role, content=content)
        )

    def add_response(self, response: InterviewResponse) -> None:
        """Record an applicant response."""
        self.responses.append(response)
        if response.is_ai_generated():
            self.total_ai_flags += 1

    def get_conversation_history(self) -> list[dict]:
        """
        Return messages formatted for Groq API.
        Maps agent → assistant, applicant → user.
        """
        return [
            {
                "role": "assistant" if m.role == MessageRole.AGENT else "user",
                "content": m.content
            }
            for m in self.messages
        ]

    def current_round_type(self) -> InterviewType:
        """Return interview type based on current round number."""
        mapping = {
            1: InterviewType.SCREENING,
            2: InterviewType.TECHNICAL,
            3: InterviewType.CULTURAL,
        }
        return mapping.get(self.current_round, InterviewType.SCREENING)

    def advance_round(self) -> bool:
        """
        Move to next round if possible.
        Returns True if advanced, False if already at final round.
        """
        if self.current_round < self.total_rounds:
            self.current_round += 1
            self.interview_type = self.current_round_type()
            return True
        return False

    def is_complete(self) -> bool:
        return self.status == SessionStatus.COMPLETED

    def has_ai_flags(self) -> bool:
        return self.total_ai_flags > 0

    def unanswered_questions(self) -> list[InterviewQuestion]:
        """Return questions that have no corresponding response."""
        answered_ids = {r.question_id for r in self.responses}
        return [q for q in self.questions if q.question_id not in answered_ids]

    def average_response_score(self) -> Optional[float]:
        """Average score across all scored responses."""
        scores = [r.score for r in self.responses if r.score is not None]
        return round(sum(scores) / len(scores), 2) if scores else None

    def compute_final_score(self) -> Optional[float]:
        """
        Average scores from all round summaries.
        Sets final_score and marks session completed.
        """
        round_scores = [
            r.round_score for r in self.round_summaries
            if r.round_score is not None
        ]
        if not round_scores:
            return None
        self.final_score = round(sum(round_scores) / len(round_scores), 2)
        self.status = SessionStatus.COMPLETED
        self.completed_at = datetime.utcnow()
        if self.started_at:
            self.duration_seconds = round(
                (self.completed_at - self.started_at).total_seconds(), 2
            )
        return self.final_score

    def summary(self) -> str:
        """One-line summary for logging."""
        return (
            f"[{self.session_id}] {self.applicant_name} | "
            f"Round {self.current_round}/{self.total_rounds} | "
            f"{self.interview_type.value} | "
            f"Status: {self.status.value} | "
            f"AI Flags: {self.total_ai_flags} | "
            f"Score: {self.final_score or 'N/A'}"
        )

    model_config = {
        "json_schema_extra": {
            "example": {
                "session_id": "SESS-001",
                "applicant_id": "INT-001",
                "applicant_name": "Aakarsh Kumar",
                "role_applied": "sde",
                "total_rounds": 3,
                "current_round": 1,
                "status": "scheduled",
            }
        }
    }