"""
models/score.py
═══════════════════════════════════════════════════════
Scoring data models for the Autonomous Hiring Agent.
Used by the Scorer Agent (Groq llama-3.3-70b-versatile)
to evaluate and rank 1000+ tech applicants.

All models use Pydantic v2.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────
#  Enums
# ─────────────────────────────────────────────────────

class ScoreGrade(str, Enum):
    """Letter grade derived from numeric score."""
    A_PLUS  = "A+"   # 90–100  → auto shortlist
    A       = "A"    # 80–89   → strong candidate
    B       = "B"    # 65–79   → consider
    C       = "C"    # 50–64   → borderline
    D       = "D"    # 35–49   → weak
    F       = "F"    # 0–34    → auto reject


class ScoringDimension(str, Enum):
    """The five dimensions scored for each applicant."""
    TECHNICAL_SKILLS    = "technical_skills"     # languages, frameworks, tools
    EXPERIENCE          = "experience"            # years + relevance of past work
    GITHUB_PORTFOLIO    = "github_portfolio"      # project quality, activity
    COVER_LETTER        = "cover_letter"          # clarity, motivation, fit
    EDUCATION           = "education"             # degree, institution, relevance


class ScoringStatus(str, Enum):
    """Current state of the scoring process."""
    PENDING     = "pending"       # not yet scored
    IN_PROGRESS = "in_progress"   # being scored by Groq
    COMPLETED   = "completed"     # score ready
    FAILED      = "failed"        # scoring error, needs retry
    SKIPPED     = "skipped"       # missing data, can't score


# ─────────────────────────────────────────────────────
#  Sub-models
# ─────────────────────────────────────────────────────

class DimensionScore(BaseModel):
    """Score for a single evaluation dimension."""
    dimension:  ScoringDimension
    score:      float   = Field(..., ge=0, le=100)
    weight:     float   = Field(..., ge=0, le=1)     # weight in final score
    reasoning:  str     = Field(..., min_length=10)  # why this score was given
    red_flags:  list[str] = Field(default_factory=list)  # concerns noted

    def weighted_score(self) -> float:
        """Return this dimension's contribution to the final score."""
        return round(self.score * self.weight, 2)


class ScoringCriteria(BaseModel):
    """
    Weights for each scoring dimension.
    Must sum to 1.0.
    Customizable per role.
    """
    technical_skills:   float = Field(default=0.35, ge=0, le=1)
    experience:         float = Field(default=0.25, ge=0, le=1)
    github_portfolio:   float = Field(default=0.20, ge=0, le=1)
    cover_letter:       float = Field(default=0.10, ge=0, le=1)
    education:          float = Field(default=0.10, ge=0, le=1)

    @field_validator("education", mode="after")
    @classmethod
    def weights_must_sum_to_one(cls, v: float, info) -> float:
        data = info.data
        total = (
            data.get("technical_skills", 0)
            + data.get("experience", 0)
            + data.get("github_portfolio", 0)
            + data.get("cover_letter", 0)
            + v
        )
        if not (0.99 <= total <= 1.01):  # allow tiny float rounding
            raise ValueError(f"Weights must sum to 1.0, got {total:.2f}")
        return v

    def to_dict(self) -> dict[str, float]:
        return {
            ScoringDimension.TECHNICAL_SKILLS:  self.technical_skills,
            ScoringDimension.EXPERIENCE:        self.experience,
            ScoringDimension.GITHUB_PORTFOLIO:  self.github_portfolio,
            ScoringDimension.COVER_LETTER:      self.cover_letter,
            ScoringDimension.EDUCATION:         self.education,
        }


# ─────────────────────────────────────────────────────
#  Core Score Model
# ─────────────────────────────────────────────────────

class ApplicantScore(BaseModel):
    """
    Full scoring result for a single applicant.
    Generated by the Scorer Agent using Groq llama-3.3-70b-versatile.
    """

    # ── Identity ──────────────────────────────────
    applicant_id:       str
    applicant_name:     str

    # ── Scoring State ─────────────────────────────
    status:             ScoringStatus   = ScoringStatus.PENDING
    scored_at:          Optional[datetime] = None
    model_used:         str             = "llama-3.3-70b-versatile"
    scoring_version:    str             = "1.0"          # bump when prompt changes

    # ── Dimension Scores ──────────────────────────
    dimension_scores:   list[DimensionScore] = Field(default_factory=list)

    # ── Final Score ───────────────────────────────
    final_score:        Optional[float] = Field(default=None, ge=0, le=100)
    grade:              Optional[ScoreGrade] = None
    rank:               Optional[int]   = None      # rank among all applicants
    percentile:         Optional[float] = Field(default=None, ge=0, le=100)

    # ── Summary ───────────────────────────────────
    strengths:          list[str]       = Field(default_factory=list)
    weaknesses:         list[str]       = Field(default_factory=list)
    overall_summary:    Optional[str]   = None
    recommendation:     Optional[str]   = None      # shortlist / reject / hold

    # ── Error Handling ────────────────────────────
    error_message:      Optional[str]   = None      # if status == FAILED

    # ── Methods ───────────────────────────────────
    def compute_final_score(self) -> float:
        """
        Calculate weighted final score from dimension scores.
        Automatically sets grade after computing.
        """
        if not self.dimension_scores:
            raise ValueError("No dimension scores to compute from")

        total = sum(d.weighted_score() for d in self.dimension_scores)
        self.final_score = round(total, 2)
        self.grade = self._assign_grade(self.final_score)
        self.scored_at = datetime.utcnow()
        self.status = ScoringStatus.COMPLETED
        return self.final_score

    @staticmethod
    def _assign_grade(score: float) -> ScoreGrade:
        """Assign letter grade based on numeric score."""
        if score >= 90:
            return ScoreGrade.A_PLUS
        elif score >= 80:
            return ScoreGrade.A
        elif score >= 65:
            return ScoreGrade.B
        elif score >= 50:
            return ScoreGrade.C
        elif score >= 35:
            return ScoreGrade.D
        else:
            return ScoreGrade.F

    def is_shortlistable(self, threshold: float = 65.0) -> bool:
        """Return True if score meets shortlist threshold."""
        return self.final_score is not None and self.final_score >= threshold

    def should_auto_reject(self, threshold: float = 35.0) -> bool:
        """Return True if score is below auto-reject threshold."""
        return self.final_score is not None and self.final_score < threshold

    def get_red_flags(self) -> list[str]:
        """Collect all red flags across all dimensions."""
        flags = []
        for d in self.dimension_scores:
            flags.extend(d.red_flags)
        return flags

    def summary_line(self) -> str:
        """One-line summary for logging and batch reports."""
        return (
            f"[{self.applicant_id}] {self.applicant_name} | "
            f"Score: {self.final_score or 'N/A'} | "
            f"Grade: {self.grade.value if self.grade else 'N/A'} | "
            f"Rank: #{self.rank or 'N/A'}"
        )


# ─────────────────────────────────────────────────────
#  Batch Scoring Model
# ─────────────────────────────────────────────────────

class BatchScoringResult(BaseModel):
    """
    Result of scoring a batch of applicants (up to 50 at a time).
    Used by the rank pipeline to process 1000+ applicants efficiently.
    """

    batch_id:           str
    batch_size:         int
    scores:             list[ApplicantScore]    = Field(default_factory=list)

    # ── Stats ─────────────────────────────────────
    total_scored:       int     = 0
    total_failed:       int     = 0
    total_skipped:      int     = 0
    average_score:      Optional[float] = None
    highest_score:      Optional[float] = None
    lowest_score:       Optional[float] = None

    # ── Timing ────────────────────────────────────
    started_at:         datetime = Field(default_factory=datetime.utcnow)
    completed_at:       Optional[datetime] = None
    duration_seconds:   Optional[float] = None

    def compute_stats(self) -> None:
        """Compute batch statistics after all scoring is done."""
        completed = [
            s for s in self.scores
            if s.status == ScoringStatus.COMPLETED
            and s.final_score is not None
        ]
        self.total_scored  = len(completed)
        self.total_failed  = sum(1 for s in self.scores if s.status == ScoringStatus.FAILED)
        self.total_skipped = sum(1 for s in self.scores if s.status == ScoringStatus.SKIPPED)

        if completed:
            all_scores = [s.final_score for s in completed]
            self.average_score = round(sum(all_scores) / len(all_scores), 2)
            self.highest_score = max(all_scores)
            self.lowest_score  = min(all_scores)

        self.completed_at = datetime.utcnow()
        self.duration_seconds = round(
            (self.completed_at - self.started_at).total_seconds(), 2
        )

    def shortlisted(self, threshold: float = 65.0) -> list[ApplicantScore]:
        """Return all applicants above shortlist threshold, sorted by score."""
        return sorted(
            [s for s in self.scores if s.is_shortlistable(threshold)],
            key=lambda s: s.final_score or 0,
            reverse=True
        )

    def rejected(self, threshold: float = 35.0) -> list[ApplicantScore]:
        """Return all applicants below auto-reject threshold."""
        return [s for s in self.scores if s.should_auto_reject(threshold)]

    def summary(self) -> str:
        return (
            f"Batch {self.batch_id} | "
            f"Scored: {self.total_scored} | "
            f"Failed: {self.total_failed} | "
            f"Avg: {self.average_score} | "
            f"Time: {self.duration_seconds}s"
        )