/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#303446',
        'inverse-primary': '#005ac2',
        'on-surface-variant': '#c2c6d6',
        'on-primary-container': '#00285d',
        'surface-container': '#1b1f30',
        'surface-container-low': '#171b2b',
        'surface-container-lowest': '#090d1d',
        'surface-container-high': '#25293b',
        'surface-container-highest': '#303446',
        'surface-bright': '#35384a',
        'surface-dim': '#0f1223',
        'surface': '#0f1223',
        'background': '#0f1223',
        'on-surface': '#dfe1f9',
        'on-background': '#dfe1f9',
        'on-primary': '#002e6a',
        'on-secondary': '#003824',
        'primary': '#adc6ff',
        'primary-container': '#4d8eff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary': '#4edea3',
        'secondary-container': '#00a572',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#d0bcff',
        'tertiary-container': '#a078ff',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'on-tertiary': '#3c0091',
        'on-tertiary-container': '#340080',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dfe1f9',
        'inverse-on-surface': '#2c2f41',
        'surface-tint': '#adc6ff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
